### ISSUE TITLE
Make test runner's BEFORE_TIMEOUT configurable

### ISSUE THREAD

**Issue by vkantchev** [trufflesuite/truffle-core#142]
Timeouts in tests are hardcoded to 2 minutes which prevents running tests on slow private networks.  Detailed description of the issues and a possible fix is available in [Truffle Issue 261](https://github.com/trufflesuite/truffle/issues/261).

**Comment by cgewecke** [comment]
Apologies @vkantchev - closing as duplicate of truffle 261 (referenced above). We're trying to keep issues in the main repo to simplify tracking.

**Comment by vkantchev** [comment]
@cgewecke  Sure. No problem. I made a comment under [Truffle Issue 261](https://github.com/trufflesuite/truffle/issues/261) too.

**Comment by cgewecke** [comment]
@vkantchev Excellent thanks. Added a suggested workaround there - please ping if that's not working.
