### ISSUE TITLE
Custom provider injected even when network not selected

### ISSUE THREAD

**Issue by Moejoe90** [trufflesuite/truffle-core#70]
- [Yes ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle injects customer provider instance even if the network is not specified for example. 
This repo was chosen because this is where Environment.js is located.
I think is due to Environment.js loading all networks instead of specifying a specific network to load
## Steps to Reproduce

you have network1 {provider: custom} network2 default you will find that both instances are projected even if network2 was chosen.

## Expected Behavior

This shouldn't be the case custom provider should be injected only if specified in this case all custom providers are injected and that causes different problems in the long run.

## Environment

* Operating System: Ubunto 17.01
* Truffle version:v4.0.1
* Ethereum client: Web3ZeroEngine
* node version: 8.8.1
* npm version: 5.5.1

**Comment by onetom** [comment]
The solution is to use factory function as the value of the `provider` config option as documented here:
http://truffleframework.com/docs/advanced/configuration#accessing-only-one-of-multiple-network-providers
this way creating the actual provider instance is delayed.

**Comment by cgewecke** [comment]
@Moejoe90, @onetom is correct - that link in the docs shows how to resolve this. 

Thanks @onetom :)

Closing for house-keeping but please feel free to re-open if you'd like more help with this.
