### ISSUE TITLE
Remove reliance on web3 solidity-coder 

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle-core#94]
@gnidan's review of #90 noticed that we rely on an internal `web3` module (`web3/lib/solidity/coder.js`)  for log decoding that will be absent or elsewhere in web3 1.0. 

Investigate replacing this with a dedicated abi utility package (or our own code) located in `truffle-solidity-utils`.

Possible candidate: [ethjs-abi](https://github.com/ethjs/ethjs-abi)

`SolidityCoder` appears in:
+ [testing/testrunner.js](https://github.com/trufflesuite/truffle-core/blob/develop/lib/testing/testrunner.js) 
+ [testing/soliditytest.js](https://github.com/trufflesuite/truffle-core/blob/develop/lib/testing/soliditytest.js)

**Comment by jtakalai** [comment]
web3 has those log decoding things exposed in web3.eth.abi without importing stuff.

Our current (pre-1.0) code has
```
const SolidityEvent = require("web3/lib/web3/event.js")
const SolidityCoder = require("web3/lib/solidity/coder.js")
```
and then does lots of log parsing from ABI, core lines being 
```
        // TODO: probably should handle somehow "If arrays (including string and bytes) are used as indexed arguments, the Keccak-256 hash of it is stored as topic instead." (http://solidity.readthedocs.io/en/develop/contracts.html#events)
        const paramTypes = event.inputs.filter(i => !i.indexed).map(i => i.type)
        const paramBytes = log.data.replace("0x", "")   // unindexed params go into data
        const paramValues = SolidityCoder.decodeParams(paramTypes, paramBytes)
```
but also noticing in comments
```
        /* web3.js 1.0 (remove direct SolidityCoder/SolidityEvent refs)
        // for anonymous events, const paramValues = web3.eth.abi.decodeLog(event.inputs, log.data, log.topics)
        const paramValues = web3.eth.abi.decodeLog(event.inputs, log.data, log.topics.slice(1))
        */
```
So yeah, I think web3.js 1.0 will greatly simplify log parsing, and that's really one of the big features I've been waiting to have from it. It's not so great to have to import stuff from the "internals".

**Comment by cgewecke** [comment]
@jtakalai Thanks for highlighting this. Cross-referencing as a reminder to [truffle-contract 95](https://github.com/trufflesuite/truffle-contract/pull/95) where iWeb3 1.0 work is currently focused.

**Comment by cgewecke** [comment]
Closing, this is done on the `web3-one` branch
